/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    fontFamily: {
      pre: ['Pretendard'],
    },
    extend: {
      colors: {
        /* Text */
        'color-text-primary': 'var(--color-neutral-900)',
        'color-text-secondary': 'var(--color-neutral-800)',
        'color-text-tertiary': 'var(--color-neutral-700)',
        'color-text-info-bold': 'var(--color-information-800)',
        'color-text-info': 'var(--color-information-600)',
        'color-text-warning-bold': 'var(--color-warning-800)',
        'color-text-warning': 'var(--color-warning-600)',
        'color-text-success-bold': 'var(--color-success-800)',
        'color-text-success': 'var(--color-success-600)',
        'color-text-danger-bold': 'var(--color-red-800)',
        'color-text-danger': 'var(--color-red-600)',
        'color-text-interactive-primary': 'var(--color-brand-600)',
        'color-text-interactive-primary-hover': 'var(--color-brand-700)',
        'color-text-interactive-primary-press': 'var(--color-brand-800)',
        'color-text-interactive-secondary': 'var(--color-neutral-600)',
        'color-text-interactive-secondary-hover': 'var(--color-neutral-700)',
        'color-text-interactive-secondary-press': 'var(--color-neutral-800)',
        'color-text-disabled': 'var(--color-neutral-500)',
        'color-text-disabled-soft': 'var(--color-neutral-200)',
        'color-text-interactive-selected': 'var(--color-brand-600)',
        'color-text-interactive-inverse': 'var(--color-base-white)',

        /* Background */
        'color-bg-primary': 'var(--color-base-white)',
        'color-bg-secondary': 'var(--color-neutral-50)',
        'color-bg-tertiary': 'var(--color-neutral-100)',
        'color-bg-info-subtle': 'var(--color-information-50)',
        'color-bg-info': 'var(--color-information-600)',
        'color-bg-warning-subtle': 'var(--color-warning-100)',
        'color-bg-warning': 'var(--color-warning-600)',
        'color-bg-success-subtle': 'var(--color-success-100)',
        'color-bg-success': 'var(--color-success-600)',
        'color-bg-danger-subtle': 'var(--color-danger-50)',
        'color-bg-danger': 'var(--color-danger-600)',
        'color-bg-disabled': 'var(--color-neutral-300)',
        'color-bg-interactive-primary': 'var(--color-brand-600)',
        'color-bg-interactive-primary-hover': 'var(--color-brand-700)',
        'color-bg-interactive-primary-press': 'var(--color-brand-800)',
        'color-bg-interactive-secondary': 'var(--color-neutral-100)',
        'color-bg-interactive-secondary-hover': 'var(--color-neutral-200)',
        'color-bg-interactive-secondary-press': 'var(--color-neutral-300)',
        'color-bg-interactive-selected': 'var(--color-brand-50)',
        'color-bg-interactive-selected-hover': 'var(--color-brand-100)',
        'color-bg-interactive-selected-press': 'var(--color-brand-200)',
        'color-bg-interactive-destructive': 'var(--color-danger-600)',
        'color-bg-interactive-destructive-hover': 'var(--color-danger-700)',
        'color-bg-interactive-destructive-press': 'var(--color-danger-800)',
        'color-bg-interactive-success': 'var(--color-green-600)',
        'color-bg-interactive-success-hover': 'var(--color-green-700)',
        'color-bg-interactive-success-press': 'var(--color-green-800)',
        'color-bg-interactive-disabled': 'var(--color-neutral-500)',
        'color-bg-interactive-disabled-hover': 'var(--color-neutral-600)',
        'color-bg-interactive-disabled-press': 'var(--color-neutral-700)',

        /* Border */
        'color-border-primary': 'var(--color-neutral-400)',
        'color-border-secondary': 'var(--color-neutral-300)',
        'color-border-tertiary': 'var(--color-neutral-200)',
        'color-border-focus-ring': 'var(--color-brand-700)',
        'color-border-info-subtle': 'var(--color-information-200)',
        'color-border-info': 'var(--color-information-600)',
        'color-border-warning-subtle': 'var(--color-warning-200)',
        'color-border-warning': 'var(--color-warning-600)',
        'color-border-success-subtle': 'var(--color-success-200)',
        'color-border-success': 'var(--color-success-600)',
        'color-border-danger-subtle': 'var(--color-danger-200)',
        'color-border-danger': 'var(--color-danger-600)',
        'color-border-disabled': 'var(--color-neutral-400)',
        'color-border-inverse': 'var(--color-base-white)',
        'color-border-interactive-primary': 'var(--color-brand-600)',
        'color-border-black': 'var(--color-base-black)',
        'color-border-interactive-primary-hover': 'var(--color-brand-700)',
        'color-border-interactive-primary-press': 'var(--color-brand-800)',
        'color-border-interactive-secondary': 'var(--color-neutral-300)',
        'color-border-interactive-secondary-hover': 'var(--color-neutral-400)',
        'color-border-interactive-secondary-press': 'var(--color-neutral-500)',

        /* Icon */
        'color-icon-primary': 'var(--color-neutral-900)',
        'color-icon-secondary': 'var(--color-neutral-800)',
        'color-icon-tertiary': 'var(--color-neutral-700)',
        'color-icon-brand': 'var(--color-brand-600)',
        'color-icon-info': 'var(--color-information-600)',
        'color-icon-warning': 'var(--color-warning-600)',
        'color-icon-success': 'var(--color-success-600)',
        'color-icon-danger': 'var(--color-danger-600)',
        'color-icon-disabled': 'var(--color-neutral-500)',
        'color-icon-interactive-primary': 'var(--color-brand-600)',
        'color-icon-interactive-primary-hover': 'var(--color-brand-700)',
        'color-icon-interactive-primary-press': 'var(--color-brand-800)',
        'color-icon-interactive-secondary': 'var(--color-neutral-600)',
        'color-icon-interactive-secondary-hover': 'var(--color-neutral-700)',
        'color-icon-interactive-secondary-press': 'var(--color-neutral-800)',
        'color-icon-interactive-selected': 'var(--color-brand-600)',
        'color-icon-interactive-inverse': 'var(--color-base-white)',
      },
      spacing: {
        'spacing-0': 'var(--unit-0)',
        'spacing-2': 'var(--unit-2)',
        'spacing-4': 'var(--unit-4)',
        'spacing-6': 'var(--unit-6)',
        'spacing-8': 'var(--unit-8)',
        'spacing-10': 'var(--unit-10)',
        'spacing-12': 'var(--unit-12)',
        'spacing-16': 'var(--unit-16)',
        'spacing-20': 'var(--unit-20)',
        'spacing-24': 'var(--unit-24)',
        'spacing-28': 'var(--unit-28)',
        'spacing-32': 'var(--unit-32)',
        'spacing-36': 'var(--unit-36)',
        'spacing-40': 'var(--unit-40)',
        'spacing-48': 'var(--unit-48)',
        'spacing-64': 'var(--unit-64)',
        'spacing-80': 'var(--unit-80)',
        'spacing-96': 'var(--unit-96)',
        'spacing-128': 'var(--unit-128)',
      },
      borderRadius: {
        'radius-0': 'var(--unit-0)',
        'radius-2': 'var(--unit-2)',
        'radius-4': 'var(--unit-4)',
        'radius-6': 'var(--unit-6)',
        'radius-8': 'var(--unit-8)',
        'radius-12': 'var(--unit-12)',
        'radius-16': 'var(--unit-16)',
        'radius-24': 'var(--unit-24)',
        'radius-32': 'var(--unit-32)',
        'radius-circle': '999999px',
      },
      keyframes: {
        slideShrink: {
          '0%': { width: '100%' },
          '99.99%': { padding: '32px' },
          '100%': { width: '0%', padding: '0' },
        },
        slideExpand: {
          '0%': { width: '0%', padding: '0' },
          '1%': { padding: '32px' },
          '100%': { width: '100%' },
        },
        slideExpandFast: {
          '0%': { width: '0%', opacity: 0 },
          '100%': { width: '100%', opacity: 1 },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '40%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeOut: {
          '0%': { opacity: '1' },
          '60%': { opacity: '0' },
          '100%': { opacity: '0' },
        },
        gapShrink: {
          '0%': { gap: '40px' },
          '100%': { gap: '0px' },
        },
        taDa: {
          '0%': { opacity: '0' },
          '99.9%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideInFromRight: {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
      },
      animation: {
        slideShrink: 'slideShrink 0.5s ease-in-out',
        slideExpand: 'slideExpand 0.5s ease-in-out',
        slideExpandFast: 'slideExpandFast 1s ease-in-out',
        fadeIn: 'fadeIn 0.5s ease-in-out',
        fadeOut: 'fadeOut 0.5s ease-in-out',
        gapShrink: 'gapShrink 0.5s ease-in-out',
        taDa: 'taDa 0.7s',
        slideInFromRight: 'slideInFromRight 0.8s ease-out',
      },
    },
  },
  plugins: [
    require('tailwind-scrollbar-hide'),
    function ({ addUtilities }) {
      const newUtilities = {
        '.heading-desktop-5xl': {
          fontSize: '64px',
          lineHeight: '120%',
          fontWeight: '700',
        },
        '.heading-desktop-4xl': {
          fontSize: '48px',
          lineHeight: '120%',
          fontWeight: '700',
        },
        '.heading-desktop-3xl': {
          fontSize: '40px',
          lineHeight: '120%',
          fontWeight: '700',
        },
        '.heading-desktop-2xl': {
          fontSize: '32px',
          lineHeight: '120%',
          fontWeight: '600',
        },
        '.heading-desktop-xl': {
          fontSize: '28px',
          lineHeight: '120%',
          fontWeight: '600',
        },
        '.heading-desktop-lg': {
          fontSize: '24px',
          lineHeight: '120%',
          fontWeight: '600',
        },
        '.heading-desktop-md': {
          fontSize: '20px',
          lineHeight: '120%',
          fontWeight: '600',
        },
        '.heading-desktop-sm': {
          fontSize: '18px',
          lineHeight: '120%',
          fontWeight: '600',
        },
        '.body-xl-semibold': {
          fontSize: '24px',
          lineHeight: '120%',
          fontWeight: '600',
        },
        '.body-xl-medium': {
          fontSize: '24px',
          lineHeight: '120%',
          fontWeight: '500',
        },
        '.body-xl-regular': {
          fontSize: '24px',
          lineHeight: '120%',
          fontWeight: '400',
        },
        '.body-lg-semibold': {
          fontSize: '20px',
          lineHeight: '120%',
          fontWeight: '600',
        },
        '.body-lg-medium': {
          fontSize: '20px',
          lineHeight: '120%',
          fontWeight: '500',
        },
        '.body-lg-regular': {
          fontSize: '20px',
          lineHeight: '120%',
          fontWeight: '400',
        },
        '.body-md-semibold': {
          fontSize: '16px',
          lineHeight: '120%',
          fontWeight: '600',
        },
        '.body-md-medium': {
          fontSize: '16px',
          lineHeight: '120%',
          fontWeight: '500',
        },
        '.body-md-regular': {
          fontSize: '16px',
          lineHeight: '120%',
          fontWeight: '400',
        },
        '.body-sm-semibold': {
          fontSize: '14px',
          lineHeight: '120%',
          fontWeight: '600',
        },
        '.body-sm-medium': {
          fontSize: '14px',
          lineHeight: '120%',
          fontWeight: '500',
        },
        '.body-sm-regular': {
          fontSize: '14px',
          lineHeight: '120%',
          fontWeight: '400',
        },
        '.body-xs-semibold': {
          fontSize: '12px',
          lineHeight: '120%',
          fontWeight: '600',
        },
        '.body-xs-medium': {
          fontSize: '12px',
          lineHeight: '120%',
          fontWeight: '500',
        },
        '.body-xs-regular': {
          fontSize: '12px',
          lineHeight: '120%',
          fontWeight: '400',
        },
      }

      addUtilities(newUtilities, ['responsive', 'hover'])
    },
  ],
}
