name: Deploy to Vercel

on:
  push:
    branches:
      - main # main 브랜치로 push할 때 실행
  pull_request:
    branches:
      - dev # dev 브랜치 대상 PR 생성 시 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub 저장소 클론
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 환경 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.13.1'

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm install

      # # 4. 테스트 실행 (선택 사항: 테스트가 없다면 생략 가능)
      # - name: Run Tests
      #   run: npm test

      # 5. Vercel로 배포.
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Vercel Personal Access Token
          vercel-args: '--prod --yes'
          working-directory: ./ # 배포할 디렉터리 (프로젝트 루트 기준).
          vercel-project-name: 'ssafice-demo'
